# Generated by Django 3.0.3 on 2020-02-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('card_name', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name='data published')),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.TextField()),
                ('card_sort', models.TextField()),
                ('card_price_min', models.IntegerField()),
                ('card_movie', models.DecimalField(decimal_places=2, max_digits=8)),
                ('card_bus', models.DecimalField(decimal_places=2, max_digits=8)),
                ('card_coffee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('card_mart', models.DecimalField(decimal_places=2, max_digits=8)),
                ('card_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
